# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug_x64
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_x64)
  raylib_config = debug_x64
  staticLib_config = debug_x64
  stellarthing_config = debug_x64

else ifeq ($(config),debug_x86)
  raylib_config = debug_x86
  staticLib_config = debug_x86
  stellarthing_config = debug_x86

else ifeq ($(config),debug_arm64)
  raylib_config = debug_arm64
  staticLib_config = debug_arm64
  stellarthing_config = debug_arm64

else ifeq ($(config),release_x64)
  raylib_config = release_x64
  staticLib_config = release_x64
  stellarthing_config = release_x64

else ifeq ($(config),release_x86)
  raylib_config = release_x86
  staticLib_config = release_x86
  stellarthing_config = release_x86

else ifeq ($(config),release_arm64)
  raylib_config = release_arm64
  staticLib_config = release_arm64
  stellarthing_config = release_arm64

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := raylib staticLib stellarthing

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

raylib:
ifneq (,$(raylib_config))
	@echo "==== Building raylib ($(raylib_config)) ===="
	@${MAKE} --no-print-directory -C raylib-master -f Makefile config=$(raylib_config)
endif

staticLib:
ifneq (,$(staticLib_config))
	@echo "==== Building staticLib ($(staticLib_config)) ===="
	@${MAKE} --no-print-directory -C staticLib -f Makefile config=$(staticLib_config)
endif

stellarthing: raylib staticLib
ifneq (,$(stellarthing_config))
	@echo "==== Building stellarthing ($(stellarthing_config)) ===="
	@${MAKE} --no-print-directory -C src -f Makefile config=$(stellarthing_config)
endif

clean:
	@${MAKE} --no-print-directory -C raylib-master -f Makefile clean
	@${MAKE} --no-print-directory -C staticLib -f Makefile clean
	@${MAKE} --no-print-directory -C src -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_x64"
	@echo "  debug_x86"
	@echo "  debug_arm64"
	@echo "  release_x64"
	@echo "  release_x86"
	@echo "  release_arm64"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   raylib"
	@echo "   staticLib"
	@echo "   stellarthing"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"